import json
import os

DATASET_PATH = "chairpal_dataset.jsonl"

def add_lifestyle_data():
    lifestyle_data = [
        # Nutrition
        {"intent": "daily_support", "language": "ar", "question": "ايه احسن اكل ليا", "answer": "نصائح التغذية المهمة لمستخدمي الكراسي المتحركة لتجنب زيادة الوزن والتهابات المسالك البولية:\n1. مراقبة السعرات الحرارية: يفضل تقليل السعرات لأن معدل الحرق يقل لعدم الوقوف أو المشي.\n2. زيادة الكالسيوم وفيتامين D3: لمنع هشاشة العظام نتيجة عدم تحميل الوزن على القدمين (يتوفر في الألبان، السبانخ، السلمون، والتونة).\n3. البروتين: مهم جداً للحفاظ على صحة الجلد وتجنب حدوث قرح الفراش والمساعدة في التئام الجروح.\n4. شرب المياة بكثرة: ضروري جداً للحفاظ على صحة الكلى والمثانة وغسل البكتيريا لتقليل خطر الإصابة بالتهابات مجرى البول (UTIs) الناتجة عن القسطرة."},
        {"intent": "daily_support", "language": "ar", "question": "تنصحني اكل ايه", "answer": "نصائح التغذية المهمة لمستخدمي الكراسي المتحركة لتجنب زيادة الوزن والتهابات المسالك البولية:\n1. مراقبة السعرات الحرارية: يفضل تقليل السعرات لأن معدل الحرق يقل لعدم الوقوف أو المشي.\n2. زيادة الكالسيوم وفيتامين D3: لمنع هشاشة العظام نتيجة عدم تحميل الوزن على القدمين (يتوفر في الألبان، السبانخ، السلمون، والتونة).\n3. البروتين: مهم جداً للحفاظ على صحة الجلد وتجنب حدوث قرح الفراش والمساعدة في التئام الجروح.\n4. شرب المياة بكثرة: ضروري جداً للحفاظ على صحة الكلى والمثانة وغسل البكتيريا لتقليل خطر الإصابة بالتهابات مجرى البول (UTIs) الناتجة عن القسطرة."},
        {"intent": "daily_support", "language": "en", "question": "what is a good diet for wheelchair users", "answer": "Important nutrition tips for wheelchair users to prevent weight gain and urinary tract infections (UTIs):\n1. Calorie Control: Watch calorie intake, as mobility-impaired individuals burn fewer calories due to not bearing weight or walking.\n2. Increase Calcium and Vitamin D3: Critical to prevent osteoporosis and maintain bone mass (found in dairy, spinach, salmon, and tuna).\n3. Protein Intake: Essential to prevent skin breakdown, avoid pressure sores, and promote wound healing.\n4. Drink Lots of Water: Crucial to flush bacteria, keep kidneys and bladder healthy, and prevent UTIs associated with catheter use."},
        
        # Exercise
        {"intent": "daily_support", "language": "ar", "question": "ايه التمارين الرياضية المناسبة ليا", "answer": "التمارين الرياضية واليوجا المناسبة لمستخدمي الكراسي المتحركة:\n1. تمارين اليوجا المعدلة (Adaptive Yoga):\n   - وضعية القطة (Cat Pose): الانحناء للأمام مع خفض الذقن وقوس الظهر.\n   - وضعية النسر (Eagle Pose): تقاطع الذراعين عند الكوع مع رفع الساعدين.\n   - إطالة الفخذ (Hip Stretch): رفع رجل فوق الأخرى والانحناء للأمام قليلاً.\n   - الالتواء (The Twist): وضع اليد اليمين على الفخذ الأيسر والدوران ليساراً.\n2. تمارين القوة والمقاومة:\n   - استخدام الأوزان الحرة أو أحبال المقاومة المرنة المقواة خلف الكرسي لتقوية الجزء العلوي والكتفين.\n   - تمارين الضغط بالكرسي (Wheelchair Push-ups) برفع الجسم عن المقعد باستخدام اليدين.\n3. التمارين الهوائية (Aerobics):\n   - الرقص بالكرسي، الجري بالكرسي على المضمار، أو الانضمام لرياضات جماعية مثل كرة السلة أو الركبي للكراسي."},
        {"intent": "daily_support", "language": "ar", "question": "عايز العب رياضة", "answer": "التمارين الرياضية واليوجا المناسبة لمستخدمي الكراسي المتحركة:\n1. تمارين اليوجا المعدلة (Adaptive Yoga):\n   - وضعية القطة (Cat Pose): الانحناء للأمام مع خفض الذقن وقوس الظهر.\n   - وضعية النسر (Eagle Pose): تقاطع الذراعين عند الكوع مع رفع الساعدين.\n   - إطالة الفخذ (Hip Stretch): رفع رجل فوق الأخرى والانحناء للأمام قليلاً.\n   - الالتواء (The Twist): وضع اليد اليمين على الفخذ الأيسر والدوران ليساراً.\n2. تمارين القوة والمقاومة:\n   - استخدام الأوزان الحرة أو أحبال المقاومة المرنة المقواة خلف الكرسي لتقوية الجزء العلوي والكتفين.\n   - تمارين الضغط بالكرسي (Wheelchair Push-ups) برفع الجسم عن المقعد باستخدام اليدين.\n3. التمارين الهوائية (Aerobics):\n   - الرقص بالكرسي، الجري بالكرسي على المضمار، أو الانضمام لرياضات جماعية مثل كرة السلة أو الركبي للكراسي."},
        {"intent": "daily_support", "language": "en", "question": "what are good exercises for wheelchair users", "answer": "Adapted exercises and yoga positions for wheelchair users:\n1. Adaptive Yoga:\n   - Cat Pose: Lean forward, drop your chin, and arch your back.\n   - Eagle Pose: Cross arms at the elbows with forearms pointing up.\n   - Hip Stretch: Lift one leg over the other and lean forward slightly.\n   - The Twist: Put your right hand on your left leg and turn to look over your left shoulder.\n2. Strength & Resistance Training:\n   - Use free weights or resistance bands secured behind the wheelchair to strengthen the upper body.\n   - Wheelchair Push-ups: Place hands on the armrests and lift your body weight off the seat.\n3. Aerobic & Cardiovascular Exercises:\n   - Wheelchair dancing, track wheeling, or joining wheelchair sports like basketball or rugby."},
        
        # Stairs
        {"intent": "wheelchair_usage", "language": "ar", "question": "ازاي الكرسي بيطلع السلم", "answer": "الكرسي بيطلع السلم من خلال ميكانيزم متطور مدمج فيه:\n1. نظام Rocker-Bogie: وهو نظام تعليق ميكانيكي (شبه المستخدم في مركبات الفضاء) بيدي الكرسي ثبات عالي وقدرة على صعود وهبوط السلالم بأمان.\n2. الرؤية الحاسوبية (Computer Vision): الكرسي بيتعرف على السلم تلقائياً من خلال كاميرا مدمجة.\n3. زر الأمان بالتطبيق: الكرسي مش بيطلع تلقائياً؛ لازم المريض يضغط أولاً على زر الأمان في الموبايل لتأكيد البدء، والكرسي بيطلع ببطء وثبات تام."},
        {"intent": "wheelchair_usage", "language": "ar", "question": "هو الكرسي بيعرف يطلع السلالم", "answer": "الكرسي بيطلع السلم من خلال ميكانيزم متطور مدمج فيه:\n1. نظام Rocker-Bogie: وهو نظام تعليق ميكانيكي (شبه المستخدم في مركبات الفضاء) بيدي الكرسي ثبات عالي وقدرة على صعود وهبوط السلالم بأمان.\n2. الرؤية الحاسوبية (Computer Vision): الكرسي بيتعرف على السلم تلقائياً من خلال كاميرا مدمجة.\n3. زر الأمان بالتطبيق: الكرسي مش بيطلع تلقائياً؛ لازم المريض يضغط أولاً على زر الأمان في الموبايل لتأكيد البدء، والكرسي بيطلع ببطء وثبات تام."},
        {"intent": "wheelchair_usage", "language": "en", "question": "how does the wheelchair climb stairs", "answer": "The wheelchair climbs stairs using an advanced integrated mechanism:\n1. Rocker-Bogie System: A mechanical suspension system (similar to those used in space rovers) providing high stability and the ability to climb and descend stairs safely.\n2. Computer Vision: The wheelchair detects stairs automatically using an integrated camera.\n3. Safety Confirmation Button: The wheelchair does not start climbing autonomously; the user must confirm it by pressing the safety button in the mobile app, and the mechanical system climbs slowly and steadily."},
    ]
    
    with open(DATASET_PATH, "a", encoding="utf-8") as f:
        for item in lifestyle_data:
            f.write(json.dumps(item, ensure_ascii=False) + "\n")
            
    print(f"Added {len(lifestyle_data)} lifestyle questions to {DATASET_PATH}")

if __name__ == "__main__":
    add_lifestyle_data()
